### ISSUE TITLE
稍后观看视频页面匹配不上这个脚本

### ISSUE THREAD

**Issue by lhard66** [kkren/bilibili_adjustPlayer#11]
例如：此地址：
https://www.bilibili.com/watchlater/#/av25741665/p1
脚本没有生效！

**Comment by lhard66** [comment]
@kkren 是否可兼容老版本播放器？因为b站还有大部分资源还是用的老版本的播放器。

**Comment by kkren** [comment]
老版本有版本的脚本，在上一条回复里

**Comment by lhard66** [comment]
@kkren 谢谢
