### ISSUE TITLE
能否加入跳过充电榜，自动下一个视频功能

### ISSUE THREAD

**Issue by WeidiDeng** [kkren/bilibili_adjustPlayer#14]
老版播放器调整有这个功能，新版的没有，希望能加上

**Comment by kkren** [comment]
![default](https://user-images.githubusercontent.com/23287823/48669211-5f0b3280-eb3a-11e8-9cb0-8910d376107b.png)
下一个视频是哪一个

**Comment by WeidiDeng** [comment]
比如这类分p的https://www.bilibili.com/video/av14184325/?p=529
