### ISSUE TITLE
[REQ] 能否增加 上次看到 xx 【自动】“跳转播放” 的功能？

### ISSUE THREAD

**Issue by waldens** [kkren/bilibili_adjustPlayer#20]
官方是：默认从头播放，要跳转播放，自己手动点一下
能否添加一个选项，允许用户：默认跳转播放，要从头播放，自己手动在时间轴上点一下？
谢谢

i![](https://i.loli.net/2018/12/08/5c0acd2d2a1cc.png)

**Comment by kkren** [comment]
官方现在默认跳转播放了好像？

**Comment by waldens** [comment]
@kkren 你那边能自动跳转是吗？我这边测试https://www.bilibili.com/video/av37545440
是重头播放，并没有自动跳转啊。难道哪里有设置开关？
