### ISSUE TITLE
菜单排版有问题

### ISSUE THREAD

**Issue by BenjaminGao** [kkren/bilibili_adjustPlayer#21]
Google Chrome | 71.0.3578.98 (正式版本) （64 位）
-- | --
操作系统 | Mac OS X 10.13.0

"恢复"的左侧有一个边框

![snipaste_2018-12-24_15-45-50](https://user-images.githubusercontent.com/16028320/50393828-dcf2d700-0793-11e9-8893-3dc4c84596b7.png)

**Comment by kkren** [comment]
行吧。。下个版本把版本号改短一点
