### ISSUE TITLE
自动宽屏后出现黑边

### ISSUE THREAD

**Issue by RicardoCM081924** [kkren/bilibili_adjustPlayer#33]
自动宽屏后上下出现黑边，且部分弹幕进入黑边，似与指定播放器大小有关，但尝试多种设置后均无法改变。
![image](https://user-images.githubusercontent.com/30168488/54406724-18a79800-4716-11e9-8605-628806e03e0d.png
)

**Comment by kkren** [comment]
指定播放器大小可能有很多问题，不建议使用。
