### ISSUE TITLE
调节速度的快捷键变为切换分P

### ISSUE THREAD

**Issue by XDcedar** [kkren/bilibili_adjustPlayer#45]
我设置的快捷键:
增加播放速度 shift + close bracket
减少播放速度 shift + open bracket

在视频加载出来之前使用快捷键不会切P, 加载出来之后用快捷键就会切换到上一P/下一P
但右键调出菜单后就能正常切换
发现问题时在看的视频: https://www.bilibili.com/video/av45641282

**Comment by kkren** [comment]
很抱歉，shift + close bracket似乎已经变成了b站自带的快捷键了？

**Comment by XDcedar** [comment]
我也发现了 所以我改成分号和单引号了 效果还不错 感谢
