### ISSUE TITLE
2020.1.8，插件似乎不可用了。

### ISSUE THREAD

**Issue by freeleefly** [kkren/bilibili_adjustPlayer#57]
【反馈】浏览器调整按钮，及之前的各种设置，都无效了。

**Comment by wialny** [comment]
我这里还可以用, 但有些许BUG, 不知道是不是此脚本的问题
普通多P视频自动跳转会在最后一秒卡住, 无限跳转
普通多P视频除了1P外都没弹幕, 弹幕列表有弹幕, 视频中为0
番剧全部0弹幕
另外还有视频无法用键盘快捷键控制

**Comment by Endermanpoi** [comment]
同问题，中午还正常，晚上失效，尝试更换存储方式无变化
在两台电脑上测试同样问题
系统：Win10 1909 和 macOS 10.15
Chrome：79.0.3945.117（79.0.3945.88同样）
插件：2.10.7

**Comment by freeleefly** [comment]
> 同问题，中午还正常，晚上失效，尝试更换存储方式无变化
> 在两台电脑上测试同样问题
> 系统：Win10 1909 和 macOS 10.15
> Chrome：79.0.3945.117（79.0.3945.88同样）
> 插件：2.10.7

我的错。
我重新copy了一份最新的2.10.7的放到油猴里，刷新，OK了。
我的现在跟你一样的环境：
系统：Win10 1909
chrome：版本 79.0.3945.117（正式版本） （64 位）
插件：2.10.7

**Comment by kkren** [comment]
如果bug还是复现的话，尽量附一份console的log。。。
