### ISSUE TITLE
浏览器收藏夹的视频依旧带有AV号，更新之后AV号视频无法使用 BUG

### ISSUE THREAD

**Issue by 881758** [kkren/bilibili_adjustPlayer#67]
浏览器收藏夹的视频依旧带有AV号，更新之后反而AV号视频无法使用 BUG

**Comment by zhengmingjiu** [comment]
在申明里添加
 // @include     http*://www.bilibili.com/video/av*
就好了

**Comment by kkren** [comment]
诶，我以为av号应该会自动跳转了

**Comment by sino1641** [comment]
> 诶，我以为av号应该会自动跳转了

+1 直到今天看到greasy上有强制av的脚本:coldsweat:
