### ISSUE TITLE
新播放器都是自动的清晰度，能不能设置默认1080之类的？

### ISSUE THREAD

**Issue by ArtOriation** [kkren/bilibili_adjustPlayer#9]

**Comment by kkren** [comment]
看了一下，现在好像又是默认最高分辨率了，可能是b站在测试dash清晰度。

**Comment by kkren** [comment]
https://www.bilibili.com/blackboard/webplayer_history.html#html5
考虑到b站正在制作记忆清晰度的功能，脚本应该不会去自行实现一个了
