### ISSUE TITLE
2.10.9版本绝大部分功能失效

### ISSUE THREAD

**Issue by sino1641** [kkren/bilibili_adjustPlayer#93]
RT，绝大部分功能，包括快捷键、播放视频和播放模式。
功能调整里的功能未测试。
可能与B站播放器样式改版有关？

**Comment by madokaa** [comment]
B站将播放器ID从 `#bofqi` 改为了 `#playerWrap` ，只需要在脚本中将这个字符串替换一下即可。

**Comment by CodesHunger** [comment]
> B站将播放器ID从 `#bofqi` 改为了 `#playerWrap` ，只需要在脚本中将这个字符串替换一下即可。

可以用了，感谢！
不过我的电脑上 定位到播放器 会直接到网页顶端， 调整小窗口大小  不能用，你的怎么样？

**Comment by madokaa** [comment]
> > B站将播放器ID从 `#bofqi` 改为了 `#playerWrap` ，只需要在脚本中将这个字符串替换一下即可。
> 
> 可以用了，感谢！
> 不过我的电脑上 定位到播放器 会直接到网页顶端， 调整小窗口大小 不能用，你的怎么样？

@CodesHunger  `定位到播放器` 功能会执行 `自动定位到播放器顶端`  里的设置, 具体可以看 `定位到播放器` 设置后的小问号.
mini播放器功能我没有使用

**Comment by CodesHunger** [comment]
@madokaa 定位播放器现在可以了，昨天不知道为什么会出问题。但是小窗口还是不行……不过算了，小窗口修改大小之后会超出浏览器，还要自己拖回来。感谢回复。

**Comment by spphinslove** [comment]
我定位播放器到顶端后不能偏移

**Comment by tenkuryu** [comment]
> B站将播放器ID从 `#bofqi` 改为了 `#playerWrap` ，只需要在脚本中将这个字符串替换一下即可。

这个好!已经解决的了!

**Comment by spphinslove** [comment]
我火狐会有时候会完全无法使用
